services:
  - type: worker
    name: TSun-DePINed-Bot
    env: python
    region: singapore
    plan: free # Note: Background Workers may not be on the free plan, please check Render's current pricing.
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4