services:
  - type: worker
    name: TSun-DePINed-Bot
    env: python
    region: singapore
    # The 'plan' is now determined by your account's subscription
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PROXY_CHOICE
        value: "2"  # 1=Free Proxyscrape, 2=Private, 3=No Proxy
      - key: ROTATE_PROXY
        value: "y"  # y=Yes, n=No
